export const galleries = [
  {
    id: 1,
    name: "Nature Wonders",
    desc: "A collection of breathtaking natural landscapes.",
    image: "./assets/gallery/g_1.png",
    slug: "nature-wonders",
    images: Array(10).fill("./assets/gallery/g_1.png"),
    date: "2025-06-01",
  },
  {
    id: 2,
    name: "Urban Stories",
    desc: "Life and moments in urban spaces.",
    image: "./assets/gallery/g_2.png",
    slug: "urban-stories",
    images: Array(10).fill("./assets/gallery/g_2.png"),
    date: "2025-07-05",
  },
  {
    id: 3,
    name: "Abstract Dimensions",
    desc: "Dive into abstract art and vibrant compositions.",
    image: "./assets/gallery/g_1.png",
    slug: "abstract-dimensions",
    images: Array(10).fill("./assets/gallery/g_1.png"),
    date: "2025-07-15",
  },
  {
    id: 4,
    name: "People & Portraits",
    desc: "Faces that tell powerful human stories.",
    image: "./assets/gallery/g_2.png",
    slug: "people-and-portraits",
    images: Array(10).fill("./assets/gallery/g_2.png"),
    date: "2025-08-01",
  },
  {
    id: 5,
    name: "Minimal Realities",
    desc: "A minimalist take on modern living and design.",
    image: "./assets/gallery/g_1.png",
    slug: "minimal-realities",
    images: Array(10).fill("./assets/gallery/g_1.png"),
    date: "2025-08-15",
  },
  {
    id: 6,
    name: "Cultural Snapshots",
    desc: "Celebrating traditions from around the world.",
    image: "./assets/gallery/g_2.png",
    slug: "cultural-snapshots",
    images: Array(10).fill("./assets/gallery/g_2.png"),
    date: "2025-09-01",
  },
  {
    id: 7,
    name: "Colors of the Night",
    desc: "Exploring the world after dark with vivid light.",
    image: "./assets/gallery/g_1.png",
    slug: "colors-of-the-night",
    images: Array(10).fill("./assets/gallery/g_1.png"),
    date: "2025-09-10",
  },
  {
    id: 8,
    name: "Historic Echoes",
    desc: "Ruins, relics, and the spirit of civilizations past.",
    image: "./assets/gallery/g_2.png",
    slug: "historic-echoes",
    images: Array(10).fill("./assets/gallery/g_2.png"),
    date: "2025-10-01",
  },
  {
    id: 9,
    name: "Wilderness Close-Up",
    desc: "Macro photography of untouched nature.",
    image: "./assets/gallery/g_1.png",
    slug: "wilderness-close-up",
    images: Array(10).fill("./assets/gallery/g_1.png"),
    date: "2025-10-10",
  },
  {
    id: 10,
    name: "The Human Lens",
    desc: "Moments of compassion, power, and resilience.",
    image: "./assets/gallery/g_2.png",
    slug: "the-human-lens",
    images: Array(10).fill("./assets/gallery/g_2.png"),
    date: "2025-10-20",
  },
];
