export const events = [
  {
    title: 'Bash Party',
    date: 'July 10, 2025',
    venue: 'Lagos Arena',
    ticketsSold: 250,
    status: 'upcoming',
    image: '',
  },
  {
    title: 'Tech Fest',
    date: 'May 20, 2025',
    venue: 'Abuja Conference Center',
    ticketsSold: 180,
    status: 'expired',
    image: '',
  },
  {
    title: 'Lagos Carnival',
    date: 'June 28, 2025',
    venue: 'Tafawa Balewa Square',
    ticketsSold: 400,
    status: 'ongoing',
    image: '',
  },
  {
    title: 'Food & Drinks Expo',
    date: 'August 12, 2025',
    venue: 'Eko Hotel',
    ticketsSold: 320,
    status: 'upcoming',
    image: '',
  },
  {
    title: 'Fashion Forward',
    date: 'April 5, 2025',
    venue: 'Landmark Center',
    ticketsSold: 150,
    status: 'expired',
    image: '',
  },
  {
    title: 'Afro Beats Night',
    date: 'June 29, 2025',
    venue: 'Freedom Park',
    ticketsSold: 500,
    status: 'ongoing',
    image: '',
  },
  {
    title: 'Comedy Blast',
    date: 'July 15, 2025',
    venue: 'Musuem Center',
    ticketsSold: 180,
    status: 'upcoming',
    image: '',
  },
  {
    title: 'Startup Showcase',
    date: 'March 18, 2025',
    venue: 'Civic Center',
    ticketsSold: 90,
    status: 'expired',
    image: '',
  },
  {
    title: 'GameCon Africa',
    date: 'June 28, 2025',
    venue: 'Lagos Tech Hub',
    ticketsSold: 200,
    status: 'ongoing',
    image: '',
  },
  {
    title: 'Wine & Chill',
    date: 'July 30, 2025',
    venue: 'VGC Garden',
    ticketsSold: 110,
    status: 'upcoming',
    image: '',
  },
  {
    title: 'Yoga In The Park',
    date: 'June 27, 2025',
    venue: 'Lekki Park',
    ticketsSold: 70,
    status: 'ongoing',
    image: '',
  },
  {
    title: 'Art Attack',
    date: 'February 14, 2025',
    venue: 'National Gallery',
    ticketsSold: 60,
    status: 'expired',
    image: '',
  },
  {
    title: 'Film Premier Night',
    date: 'July 12, 2025',
    venue: 'Silverbird Galleria',
    ticketsSold: 340,
    status: 'upcoming',
    image: '',
  },
  {
    title: 'Hackathon Nigeria',
    date: 'June 28, 2025',
    venue: 'Tech Bridge',
    ticketsSold: 290,
    status: 'ongoing',
    image: '',
  },
  {
    title: 'Green Earth Forum',
    date: 'May 5, 2025',
    venue: 'UNILAG Hall',
    ticketsSold: 140,
    status: 'expired',
    image: '',
  },
  {
    title: 'Cultural Showcase',
    date: 'August 5, 2025',
    venue: 'Oba Square',
    ticketsSold: 390,
    status: 'upcoming',
    image: '',
  },
  {
    title: 'Book Festival',
    date: 'March 9, 2025',
    venue: 'CMS Library',
    ticketsSold: 220,
    status: 'expired',
    image: '',
  },
  {
    title: 'DevFest Lagos',
    date: 'June 28, 2025',
    venue: 'Yaba Tech Arena',
    ticketsSold: 600,
    status: 'ongoing',
    image: '',
  },
  {
    title: 'Beach Hangout',
    date: 'July 20, 2025',
    venue: 'Elegushi Beach',
    ticketsSold: 160,
    status: 'upcoming',
    image: '',
  },
  {
    title: 'Indie Music Fest',
    date: 'April 10, 2025',
    venue: 'Surulere Dome',
    ticketsSold: 300,
    status: 'expired',
    image: '',
  },
];
